version: '3.9'
services:      
    web_t:
        build: .
        restart: always
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
        - .:/code
        ports:
        - "8000:8000"
        depends_on:
        - rabbitmq_t
    cond:
        image: django_rabbit_pika-web_t
        restart: always
        command: >
            bash -c "python ./manage.py cond"
        volumes:
        - .:/code
        ports:
        - "8001:8000"
        depends_on:
        - rabbitmq_t
    rabbitmq_t:
        image: "rabbitmq:3-management"
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        expose:
            - 15672
            - 5672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/home/log/rabbitmq
        networks:
            - rabbitmq_go_net


networks:
  rabbitmq_go_net:
    driver: bridge
